### ISSUE TITLE
Game Compatibility?

### ISSUE THREAD

**Issue by madmaxgrey** [cameronjohnstonmusic/steam-achievement-tracker#1]
does this work for all games or just fallout 4

**Comment by cameronjohnstonmusic** [comment]
Works for any game on stream. The [documentation](https://docs.google.com/document/d/1cOEb08vyI1qMYgD680Uwg1Z0VZ33Url84lMTWjTYfdE/edit?usp=sharing) shows how you can edit the program to work with any game.
